version: '3'

services:
  wsg50app:
    build:
        context: .
        dockerfile: "Dockerfile.dockerfile"
        network: host
    container_name: wsg50
    #command: sh -c "sleep 10s ; python ./main.py"
    tty: true